import { MIN_LETTERS, MAX_LETTERS } from './settings';

/**
 * Where the game gets its words. The list is split into small shards that are
 * fetched on demand, so nothing here needs the whole list in memory.
 */
export interface WordSource {
	/** Whether `word` is in the word list. */
	isValid(word: string): Promise<boolean>;
	/** A word from the list, chosen with `random` (any function giving numbers in [0, 1)). */
	pickAnswer(random?: () => number): Promise<string>;
}

/** Reads a file from the static/words directory, e.g. `index.json` or `8-s.txt`. */
export type FetchText = (file: string) => Promise<string>;

/** Which shard holds a word: its length and first letter, e.g. `8-s` for "sabotage". */
const shardKey = (word: string) => `${word.length}-${word[0]}`;

/**
 * Makes a word source that loads shards with `fetchText` and remembers them.
 * Shards and the index are generated by scripts/build-words.mjs.
 */
export const createWordSource = (fetchText: FetchText): WordSource => {
	// Cache the promises so concurrent lookups share one request; forget failures so they can retry
	const cache = new Map<string, Promise<unknown>>();
	const cached = <T>(key: string, load: () => Promise<T>): Promise<T> => {
		let promise = cache.get(key) as Promise<T> | undefined;
		if (!promise) {
			promise = load();
			cache.set(key, promise);
			promise.catch(() => cache.delete(key));
		}
		return promise;
	};

	const loadIndex = () =>
		cached(
			'index',
			async () => JSON.parse(await fetchText('index.json')) as Record<string, number>
		);

	const loadShard = (key: string) =>
		cached(key, async () => new Set((await fetchText(`${key}.txt`)).split('\n').filter(Boolean)));

	return {
		async isValid(word) {
			if (word.length < MIN_LETTERS || word.length > MAX_LETTERS || !/^[a-z]+$/.test(word)) {
				return false;
			}
			const key = shardKey(word);
			// Check the index first: not every length/letter pair has a shard
			if (!((await loadIndex())[key] > 0)) return false;
			return (await loadShard(key)).has(word);
		},

		async pickAnswer(random = Math.random) {
			const index = await loadIndex();
			// Weight each shard by its size so every word is equally likely
			const entries = Object.entries(index);
			let pick = Math.floor(random() * entries.reduce((sum, [, count]) => sum + count, 0));
			const [key] = entries.find(([, count]) => (pick -= count) < 0) ?? entries[entries.length - 1];
			const words = [...(await loadShard(key))];
			return words[Math.floor(random() * words.length)];
		}
	};
};
